
project_id = "yyrmodgbnzqbmatlypuc"

[functions.send-lineup-email]
verify_jwt = false

[functions.schedule-lineup-emails]
verify_jwt = false

[functions.gmail-auth]
verify_jwt = false

[functions.generate-schedule-xml]
verify_jwt = false

[functions.schedule-xml-refresh]
verify_jwt = false

